### ISSUE TITLE
Transferring ownership of this repo

### ISSUE THREAD

**Issue by vincentfretin** [mozilla/naf-janus-adapter#109]
I know Hubs doesn't use this code anymore. Some users like me still uses it in NAF projects.
I'm currently maintaining master and a 3.0.x branch in my fork https://github.com/Synantoo/naf-janus-adapter
I'm just wondering if I should move my fork to the networked-aframe organization or move the original repository there.

Instead of archiving this repo like @brianpeiris said, are you interested of transferring the ownership of this repo to the https://github.com/networked-aframe organization? Or give me the edit permission here?
I would like to make new releases like 3.0.21 on npmjs too.
cc @netpro2k @robertlong @mqp

**Comment by mqp** [comment]
It seems like it would make the most sense to belong to the NAF org, but I am happy to take custody of whatever (and do minimum viable maintenance) if it's convenient for anyone.

**Comment by brianpeiris** [comment]
Transferring this repo is not very straight-forward. Since it is part of the mozilla organization, I believe we'd have to contact a super-admin to do the transfer for us, if it's even an option.

Unless there's a strong reason to prefer a transfer, forking would be the easier route. We could archive this repo and change the README to recommend people move over to the community fork.

There's also the matter of the npm package. I think there are similar security and trust issues there. Taking it from a consumer's perspective, I'm not sure how I would feel if a package transferred ownership from one organization to a community-lead group without me knowing, so for that reason it may also make sense to start publishing the community fork under a new name, or a scoped name and we can again change the npm README to recommend the community package.

**Comment by vincentfretin** [comment]
Thanks you for the replies. I want to freely update the documentation in the repo, so I'll continue updating my fork. I moved it to the networked-aframe organization and just created the networked-aframe organization on npmjs.com so we can release scoped packages like `@networked-aframe/janus` in the future. @mqp I added you with role Maintain in the repo and added you as member of the networked-aframe organization on npmjs.com as well.
